reviews:
  auto_title_placeholder: '@coderabbitai'

  high_level_summary: true
  high_level_summary_in_walkthrough: true

  poem: false
  review_status: true
  collapse_walkthrough: true

  auto_review:
    enabled: true
    auto_incremental_review: true
